table FactAprovacoesAposPrecoParceiro
	lineageTag: 7987b794-46ba-4bb9-ba23-87293d39b395

	column NumeroOS
		dataType: int64
		formatString: 0
		lineageTag: d694095a-2cfb-4b2e-8e0d-f4360a0372dd
		summarizeBy: sum
		sourceColumn: NumeroOS

		annotation SummarizationSetBy = Automatic

	column CodigoCliente
		dataType: string
		lineageTag: 23f2fb56-b975-4bc6-911c-db395d0816bb
		summarizeBy: none
		sourceColumn: CodigoCliente

		annotation SummarizationSetBy = Automatic

	column NomeCliente
		dataType: string
		lineageTag: 80d5fe9b-0422-4c33-8836-63fd30255622
		summarizeBy: none
		sourceColumn: NomeCliente

		annotation SummarizationSetBy = Automatic

	column DataAprovacao
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9ca18c1e-6f76-48cb-a077-b0b8ac7e2c69
		summarizeBy: none
		sourceColumn: DataAprovacao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AprovacaoAutomatica
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fce2ffee-7f3d-4697-9e07-401652c00680
		summarizeBy: none
		sourceColumn: AprovacaoAutomatica

		annotation SummarizationSetBy = Automatic

	column TipoManutencao
		dataType: string
		lineageTag: 793cf1e8-613c-4424-847f-c0577921e8f6
		summarizeBy: none
		sourceColumn: TipoManutencao

		annotation SummarizationSetBy = Automatic

	column ValorAprovado
		dataType: double
		lineageTag: 7cf8fb82-865f-4425-85a8-0faa6544ef29
		summarizeBy: sum
		sourceColumn: ValorAprovado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalItensAprovadosNegociados
		dataType: int64
		formatString: 0
		lineageTag: 6d8752d6-f6e9-48ee-8b12-437eb6d20eef
		summarizeBy: sum
		sourceColumn: TotalItensAprovadosNegociados

		annotation SummarizationSetBy = Automatic

	column ValorAprovadoNegociado
		dataType: double
		lineageTag: ab62cf96-05e2-48a6-b7d7-00e3815036d6
		summarizeBy: sum
		sourceColumn: ValorAprovadoNegociado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactAprovacoesAposPrecoParceiro = m
		mode: import
		queryGroup: Fatos
		source =
				let
				    Fonte = Azure("WITH CTE AS (#(lf)  SELECT#(lf)    fmi.Sk_MaintenanceItem#(lf)    , fmi.MaintenanceID#(lf)    , fmi.PartPriceApproved#(lf)  FROM hive_metastore.gold.fact_maintenanceitems AS fmi#(lf)  #(lf)    LEFT JOIN hive_metastore.gold.dim_maintenancelogpriceregulatorpartner AS pr1#(lf)      ON pr1.PricePartReferencePriceNegId = fmi.PartPriceNegociatedId#(lf)#(lf)    LEFT JOIN hive_metastore.gold.dim_maintenancelogpriceregulatorpartner AS pr2#(lf)      ON pr2.PricePartReferencePriceNegId = fmi.PartPriceNegociatedCustomerId#(lf)#(lf)    LEFT JOIN hive_metastore.gold.dim_maintenancelabors AS dml#(lf)      ON fmi.Sk_MaintenanceLabor = dml.Sk_MaintenanceLabor#(lf)  #(lf)  WHERE 1=1#(lf)    AND fmi.ApprovalTimestamp IS NOT NULL#(lf)    AND (pr1.Sk_PriceRegulatorPartner IS NOT NULL OR pr2.Sk_PriceRegulatorPartner IS NOT NULL)#(lf)    AND (dml.LaborName IS NULL OR dml.LaborName NOT LIKE '%GUINCHO%')#(lf))#(lf)SELECT#(lf)    fms.OrderServiceCode                                           AS NumeroOS#(lf)  , COUNT(DISTINCT CTE.Sk_MaintenanceItem)                         AS TotalItensAprovadosNegociados#(lf)  , SUM(CTE.PartPriceApproved)                                     AS ValorAprovadoNegociado#(lf)  , (fms.PartValue + fms.LaborValue)                               AS ValorAprovado#(lf)  , dfc.CustomerSourceCode                                         AS CodigoCliente#(lf)  , dfc.CustomerShortName                                          AS NomeCliente#(lf)  , date_format(fms.ApprovalTimestamp, 'yyyy-MM-dd')               AS DataAprovacao#(lf)  , dmt.MaintenanceType                                            AS TipoManutencao#(lf)  , fms.IsAutomaticApproval                                        AS AprovacaoAutomatica #(lf)#(lf)FROM hive_metastore.gold.fact_maintenanceservices AS fms#(lf)  #(lf)  LEFT JOIN hive_metastore.gold.dim_fuelcustomers AS dfc#(lf)    ON fms.Sk_FuelCustomer = dfc.Sk_FuelCustomer#(lf)  #(lf)  LEFT JOIN hive_metastore.gold.dim_maintenancetypes AS dmt#(lf)    ON fms.Sk_MaintenanceType = dmt.Sk_MaintenanceType#(lf)  #(lf)  RIGHT JOIN CTE#(lf)    ON CTE.maintenanceid = fms.OrderServiceCode#(lf)#(lf)WHERE 1=1#(lf)  AND fms.ApprovalTimestamp >= '2025-04-01' #(lf)  AND fms.OrderServiceCode = 18748595 -----------------------------Testando#(lf)#(lf)GROUP BY#(lf)    fms.OrderServiceCode#(lf)  , fms.PartValue#(lf)  , fms.LaborValue#(lf)  , dfc.CustomerSourceCode#(lf)  , dfc.CustomerShortName#(lf)  , fms.ApprovalTimestamp#(lf)  , dmt.MaintenanceType#(lf)  , fms.IsAutomaticApproval"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"CodigoCliente", type text}, {"DataAprovacao", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

