table FactAprovacaoPrecoParceiro
	lineageTag: 124713ca-bad0-4c4a-9441-516265afee93

	column NumeroOS
		dataType: int64
		formatString: 0
		displayFolder: _OS
		lineageTag: b88dfb2a-354d-40a7-99e6-321e9f7d8546
		summarizeBy: none
		sourceColumn: NumeroOS

		annotation SummarizationSetBy = Automatic

	column TipoOS
		dataType: string
		displayFolder: _OS
		lineageTag: 803efe58-e083-4b7a-9bb9-b2f08204181f
		summarizeBy: none
		sourceColumn: TipoOS

		annotation SummarizationSetBy = Automatic

	column DataAprovacao1OS
		dataType: dateTime
		formatString: Short Date
		displayFolder: _OS
		lineageTag: 94414d46-fdde-4cd7-8d17-445823ff3d6b
		summarizeBy: none
		sourceColumn: DataAprovacao1OS

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NomeUsuario
		dataType: string
		displayFolder: _Aprovador
		lineageTag: 43472e5a-e891-4e28-886f-0be477ab7186
		summarizeBy: none
		sourceColumn: NomeUsuario

		annotation SummarizationSetBy = Automatic

	column CodigoUsuario
		dataType: int64
		formatString: 0
		displayFolder: _Aprovador
		lineageTag: a1cd5bd8-43f0-4692-8b1a-8b5079d139de
		summarizeBy: sum
		sourceColumn: CodigoUsuario

		annotation SummarizationSetBy = Automatic

	column CodigoModeloManutencao
		dataType: int64
		formatString: 0
		displayFolder: _Cliente
		lineageTag: cdcc8732-70ad-42af-a2de-77f54efd755e
		summarizeBy: sum
		sourceColumn: CodigoModeloManutencao

		annotation SummarizationSetBy = Automatic

	column NomeCliente
		dataType: string
		displayFolder: _Cliente
		lineageTag: f5b649a1-9787-4c55-915d-00b88355ff50
		summarizeBy: none
		sourceColumn: NomeCliente

		annotation SummarizationSetBy = Automatic

	column CodigoCliente
		dataType: string
		displayFolder: _Cliente
		lineageTag: 34504bff-a297-4821-886e-333120aadf8e
		summarizeBy: none
		sourceColumn: CodigoCliente

		annotation SummarizationSetBy = Automatic

	column InformacaoAdicional2
		dataType: string
		displayFolder: _Cliente
		lineageTag: f0576833-b6a9-4b44-b9d4-44b1e5d74e31
		summarizeBy: none
		sourceColumn: InformacaoAdicional2

		annotation SummarizationSetBy = Automatic

	column CodigoEC
		dataType: int64
		formatString: 0
		displayFolder: _EC
		lineageTag: 97137867-0c14-49a8-8eb1-ff44b129b783
		summarizeBy: sum
		sourceColumn: CodigoEC

		annotation SummarizationSetBy = Automatic

	column NomeEC
		dataType: string
		displayFolder: _EC
		lineageTag: de24c6b3-d2bc-483f-8c2e-ef609f302fa3
		summarizeBy: none
		sourceColumn: NomeEC

		annotation SummarizationSetBy = Automatic

	column TipoEC
		dataType: string
		displayFolder: _EC
		lineageTag: 67b71895-2f4b-4871-b5a0-271f0f2fb3c9
		summarizeBy: none
		sourceColumn: TipoEC

		annotation SummarizationSetBy = Automatic

	column UFEC
		dataType: string
		displayFolder: _EC
		lineageTag: 7d8bfbae-95d4-483a-a169-a30a7b9f86a0
		summarizeBy: none
		sourceColumn: UFEC

		annotation SummarizationSetBy = Automatic

	column CidadeEC
		dataType: string
		displayFolder: _EC
		lineageTag: 11f15831-236b-4f88-8868-2790610b3745
		summarizeBy: none
		sourceColumn: CidadeEC

		annotation SummarizationSetBy = Automatic

	column ChaveItem
		dataType: int64
		formatString: 0
		displayFolder: _Peça
		lineageTag: 77e1994f-afc3-4715-95dd-12641816b401
		summarizeBy: sum
		sourceColumn: ChaveItem

		annotation SummarizationSetBy = Automatic

	column NomePeca
		dataType: string
		displayFolder: _Peça
		lineageTag: db224a2a-2d7b-4f78-90c1-fafcfaba9e20
		summarizeBy: none
		sourceColumn: NomePeca

		annotation SummarizationSetBy = Automatic

	column ComplementoConcatenadoPeca
		dataType: string
		displayFolder: _Peça
		lineageTag: aa0ad2af-bd66-415f-8832-63d5515cdcd1
		summarizeBy: none
		sourceColumn: ComplementoConcatenadoPeca

		annotation SummarizationSetBy = Automatic

	column FabricantePeca
		dataType: string
		displayFolder: _Peça
		lineageTag: 4443f7a9-1580-4063-a1ae-c54cd8bea674
		summarizeBy: none
		sourceColumn: FabricantePeca

		annotation SummarizationSetBy = Automatic

	column QuantidadePeca
		dataType: double
		displayFolder: _ValoresAprovação
		lineageTag: 5e0f94a9-a636-4481-839c-87af92ab51ed
		summarizeBy: sum
		sourceColumn: QuantidadePeca

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ValorUnitarioPeca
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: _ValoresAprovação
		lineageTag: 97904c0e-a96c-4446-a9f4-9c17a1b0de83
		summarizeBy: sum
		sourceColumn: ValorUnitarioPeca

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column ValorTotalPeca
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: _ValoresAprovação
		lineageTag: 32340e4a-81f1-4e35-a14a-c3d81bca7baa
		summarizeBy: sum
		sourceColumn: ValorTotalPeca

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column ValorUnitarioNegociado
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: _PrecoReferencial/Negociado
		lineageTag: 909f8960-32f0-40e8-b331-8415740512aa
		summarizeBy: sum
		sourceColumn: ValorUnitarioNegociado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column ValorUnitarioReferencial
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: _PrecoReferencial/Negociado
		lineageTag: f173f368-0b78-449c-a4c8-2d3a0e0cfe23
		summarizeBy: sum
		sourceColumn: ValorUnitarioReferencial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column ValorUnitarioHierarquiaReferencial
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: _PrecoReferencial/Negociado
		lineageTag: 7efa2741-b22b-4fd0-88bd-4b09e9dcf2dd
		summarizeBy: sum
		sourceColumn: ValorUnitarioHierarquiaReferencial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column ValorTotalHierarquiaReferencial
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: _PrecoReferencial/Negociado
		lineageTag: e5fc7058-fd5b-439e-9987-13ac6ef845d6
		summarizeBy: sum
		sourceColumn: ValorTotalHierarquiaReferencial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column AderenciaPrecoReferencial
		dataType: string
		displayFolder: _PrecoReferencial/Negociado
		lineageTag: 6519f2e2-bfaa-4454-ab75-e9031078508e
		summarizeBy: none
		sourceColumn: AderenciaPrecoReferencial

		annotation SummarizationSetBy = Automatic

	column DataEnvioNegociacaoPrecoParceiro
		dataType: dateTime
		formatString: General Date
		displayFolder: _PreçoParceiro
		lineageTag: e93185c6-257b-445f-9308-80c263190e8c
		summarizeBy: none
		sourceColumn: DataEnvioNegociacaoPrecoParceiro

		annotation SummarizationSetBy = Automatic

	column ValorUnitarioNegociadoPrecoParceiro
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: _PreçoParceiro
		lineageTag: dc0af61a-366c-4d14-8c85-39bc4a69f190
		summarizeBy: sum
		sourceColumn: ValorUnitarioNegociadoPrecoParceiro

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column ValidadeNegociacaoMeses
		dataType: int64
		formatString: 0
		displayFolder: _PreçoParceiro
		lineageTag: 4fa4f2b5-574d-460b-a4d0-ba0aa87dbe93
		summarizeBy: sum
		sourceColumn: ValidadeNegociacaoMeses

		annotation SummarizationSetBy = Automatic

	column ValorTotalNegociadoPrecoParceiro
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: _PreçoParceiro
		lineageTag: 31fed204-1b8b-4a14-a72c-0fbc12daf832
		summarizeBy: sum
		sourceColumn: ValorTotalNegociadoPrecoParceiro

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column DiferencaValorUnitarioReferencialXNeggociado
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 98711aff-3666-416e-a9f4-6b387e793e3f
		summarizeBy: sum
		sourceColumn: DiferencaValorUnitarioReferencialXNeggociado

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column '% DiferencaNegociadoXReferencialHierarquia' =
			
			DIVIDE(FactAprovacaoPrecoParceiro[DiferencaValorUnitarioReferencialXNeggociado],FactAprovacaoPrecoParceiro[ValorUnitarioHierarquiaReferencial])
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: d272d3c7-1fe4-4f27-b3c4-3383e7f9dd2e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition FactAprovacaoPrecoParceiro = m
		mode: import
		queryGroup: Fatos
		source =
				let
				    Fonte = Azure("WITH param_logs AS (#(lf)  SELECT#(lf)    dmplv.ClientId AS CodigoCliente,#(lf)    CAST(dmplv.ParameterLogOrgValueModificationTimestamp AS TIMESTAMP) AS ts,#(lf)    COALESCE(dmplv.OldValueDescription, '') AS old_values,#(lf)    COALESCE(dmplv.NewValueDescription, '') AS new_values#(lf)  FROM hive_metastore.gold.Dim_MaintenanceParameterLogValue AS dmplv#(lf)  WHERE dmplv.ParameterId = 586#(lf)),#(lf)-- Normaliza old/new em arrays (aceita ; ou , como separadores; remove espaços, vazios e duplicados)#(lf)sets AS (#(lf)  SELECT#(lf)    CodigoCliente,#(lf)    ts,#(lf)    array_distinct(#(lf)      filter(#(lf)        split(regexp_replace(old_values, '\\s+', ''), '[;,]+'),#(lf)        x -> x <> ''#(lf)      )#(lf)    ) AS old_set,#(lf)    array_distinct(#(lf)      filter(#(lf)        split(regexp_replace(new_values, '\\s+', ''), '[;,]+'),#(lf)        x -> x <> ''#(lf)      )#(lf)    ) AS new_set#(lf)  FROM param_logs#(lf)),#(lf)-- Inclusões (ADD): itens presentes no new_set e ausentes no old_set#(lf)adds AS (#(lf)  SELECT#(lf)    CodigoCliente,#(lf)    ts,#(lf)    CAST(approver AS STRING) AS approver#(lf)  FROM sets#(lf)  LATERAL VIEW explode(new_set) ns AS approver#(lf)  WHERE NOT array_contains(old_set, approver)#(lf)),#(lf)-- Exclusões (REMOVE): itens presentes no old_set e ausentes no new_set#(lf)removes AS (#(lf)  SELECT#(lf)    CodigoCliente,#(lf)    ts,#(lf)    CAST(approver AS STRING) AS approver#(lf)  FROM sets#(lf)  LATERAL VIEW explode(old_set) os AS approver#(lf)  WHERE NOT array_contains(new_set, approver)#(lf)),#(lf)events AS (#(lf)  SELECT CodigoCliente, approver, ts, 'ADD'    AS event_type FROM adds#(lf)  UNION ALL#(lf)  SELECT CodigoCliente, approver, ts, 'REMOVE' AS event_type FROM removes#(lf)),#(lf)-- Para cada Cliente+Aprovador, calcula LEAD sobre TODOS os eventos antes de filtrar#(lf)ordered_events AS (#(lf)  SELECT#(lf)    CodigoCliente,#(lf)    approver,#(lf)    event_type,#(lf)    ts,#(lf)    LEAD(ts) OVER (PARTITION BY CodigoCliente, approver ORDER BY ts) AS DataFim#(lf)  FROM events#(lf)),#(lf)-- Filtra apenas ADDs, agora com DataFim correto (apontando para o REMOVE)#(lf)param_intervals AS (#(lf)  SELECT#(lf)    CodigoCliente,#(lf)    approver AS Aprovador,#(lf)    ts AS DataInicio,#(lf)    DataFim#(lf)  FROM ordered_events#(lf)  WHERE event_type = 'ADD'#(lf)),#(lf)----------------------------------------------------------------------------------------------------------------------------------#(lf)#(lf)tabela_preco_parceiro AS (#(lf)  SELECT DISTINCT OrderServiceId#(lf)  FROM gold.dim_maintenancelogpriceregulatorpartner#(lf)  WHERE SendDate IS NOT NULL#(lf))#(lf)#(lf)#(lf)#(lf)-------------------------------------------------------------------------------------------------------------------------------------#(lf)SELECT#(lf)    fmi.MaintenanceId                                                       AS NumeroOS,#(lf)    fmt.MaintenanceType                                                     AS TipoOS,#(lf)    fms.FirstApprovalTimestamp                                              AS DataAprovacao1OS,#(lf)#(lf)    dwu.WebUserName                                                         AS NomeUsuario,#(lf)    dwu.WebUserSourceCode                                                   AS CodigoUsuario,#(lf)#(lf)    dmv.MaintenanceVehicleModelId                                           AS CodigoModeloManutencao,#(lf)    dfc.CustomerShortName                                                   AS NomeCliente,#(lf)    dmv.CustomerId                                                          AS CodigoCliente,#(lf)    dmv.AdditionalInformation2Description                                   AS InformacaoAdicional2,#(lf)#(lf)    dmm.SourceNumber                                                        AS CodigoEC,#(lf)    dmm.MerchantShortenedName                                               AS NomeEC,#(lf)    dmm.NameMerchantsTypes                                                  AS TipoEC,#(lf)    dmm.StateName                                                           AS UFEC,#(lf)    dmm.CityName                                                            AS CidadeEC,#(lf)#(lf)#(lf)    fmi.Sk_MaintenanceItem                                                  AS ChaveItem,#(lf)    dmp.PartName                                                            AS NomePeca,#(lf)    dmc.ComplementDescription                                               AS ComplementoConcatenadoPeca,#(lf)    dmif.PartManufacturerName                                               AS FabricantePeca,#(lf)#(lf)    fmi.PartQuantity                                                        AS QuantidadePeca,#(lf)    fmi.PartUnitaryPrice                                                    AS ValorUnitarioPeca,#(lf)    QuantidadePeca * ValorUnitarioPeca                                      AS ValorTotalPeca,#(lf)#(lf)    COALESCE(fmi.PartPriceNegociatedCustomer, fmi.PartPriceNegociated)      AS ValorUnitarioNegociado,#(lf)    COALESCE(fmi.PartPriceReferenceCustomer, fmi.PartReferencePrice)        AS ValorUnitarioReferencial,#(lf)    COALESCE(ValorUnitarioNegociado,ValorUnitarioReferencial)               AS ValorUnitarioHierarquiaReferencial,#(lf)    QuantidadePeca * ValorUnitarioHierarquiaReferencial                     AS ValorTotalHierarquiaReferencial,#(lf)#(lf)    CASE#(lf)      WHEN ValorUnitarioPeca IS NULL THEN 'NA'#(lf)      WHEN ValorUnitarioPeca <= 0.01 THEN 'NA'#(lf)      WHEN ValorUnitarioHierarquiaReferencial IS NULL THEN 'NA'#(lf)      WHEN ValorUnitarioHierarquiaReferencial <= 0.01 THEN 'NA'#(lf)      WHEN ValorUnitarioPeca > ValorUnitarioHierarquiaReferencial THEN 'NOK'#(lf)      ELSE 'OK' END                                                         AS AderenciaPrecoReferencial,#(lf)#(lf)    dmlprp.SendDate                                                         AS DataEnvioNegociacaoPrecoParceiro,#(lf)    dmlprp.PricePartInfo                                                    AS InfoPrecoParceiro#(lf)    #(lf)    #(lf)    #(lf)    #(lf)    #(lf)    #(lf)#(lf)FROM hive_metastore.gold.fact_maintenanceitems AS fmi#(lf)#(lf)  LEFT JOIN hive_metastore.gold.dim_maintenanceparts AS dmp#(lf)    ON fmi.Sk_MaintenancePart = dmp.Sk_MaintenancePart#(lf)#(lf)  LEFT JOIN hive_metastore.gold.dim_maintenancecomplements AS dmc#(lf)    ON fmi.Sk_MaintenanceComplement = dmc.Sk_MaintenanceComplement#(lf)#(lf)  LEFT JOIN hive_metastore.gold.fact_maintenanceservices AS fms#(lf)    ON fmi.MaintenanceId = fms.OrderServiceCode#(lf)#(lf)  LEFT JOIN hive_metastore.gold.dim_maintenancetypes AS fmt#(lf)    ON fms.Sk_MaintenanceType = fmt.Sk_MaintenanceType#(lf)#(lf)  LEFT JOIN hive_metastore.gold.dim_maintenancemerchants AS dmm#(lf)    ON fms.Sk_MaintenanceMerchant = dmm.Sk_MaintenanceMerchant#(lf)#(lf)  LEFT JOIN hive_metastore.gold.dim_maintenancevehicles AS dmv#(lf)    ON fms.Sk_MaintenanceVehicle = dmv.Sk_MaintenanceVehicle#(lf)#(lf)  LEFT JOIN hive_metastore.gold.dim_fuelcustomers AS dfc#(lf)    ON fms.Sk_FuelCustomer = dfc.Sk_FuelCustomer#(lf)#(lf)  LEFT JOIN hive_metastore.gold.dim_webusers AS dwu#(lf)    ON fms.FirstApproverCode = dwu.WebUserSourceCode#(lf)  #(lf)  LEFT JOIN gold.dim_maintenancelogpriceregulatorpartner AS dmlprp#(lf)    ON fmi.MaintenanceItemSourceCode = dmlprp.OrderServiceItemId#(lf)#(lf)  LEFT JOIN hive_metastore.gold.dim_maintenanceitemmanufacturers AS dmif#(lf)    ON fmi.Sk_ServiceItemManufacturer = dmif.Sk_ServiceItemManufacturer#(lf)#(lf)  LEFT JOIN tabela_preco_parceiro#(lf)    ON fmi.MaintenanceId = tabela_preco_parceiro.OrderServiceId#(lf)#(lf)  LEFT JOIN hive_metastore.gold.dim_maintenancelabors AS dml#(lf)    ON fmi.Sk_MaintenanceLabor = dml.Sk_MaintenanceLabor#(lf)#(lf)WHERE 1=1#(lf)  AND fmi.CancellationTimestamp IS NULL#(lf)  AND fmi.ItemDisapprovalTimestamp IS NULL#(lf)  AND fms.FirstApprovalTimestamp >= TIMESTAMP '2025-04-01'#(lf)  -- Excluir serviços de guincho#(lf)  AND (dml.LaborName IS NULL OR dml.LaborName NOT LIKE '%GUINCHO%')#(lf)  -- Filtro de aprovadores ativos: apenas aprovadores que estavam ativos na data de aprovação E que continuam ativos#(lf)  AND (#(lf)    -- Caso 1: OS com negociação de preço parceiro (sempre incluir)#(lf)    tabela_preco_parceiro.OrderServiceId IS NOT NULL#(lf)    OR#(lf)    -- Caso 2: Aprovador estava ativo na data de aprovação da OS (DataInicio <= DataAprovacao1OS < DataFim)#(lf)    EXISTS (#(lf)      SELECT 1#(lf)      FROM param_intervals pi#(lf)      WHERE pi.CodigoCliente = dmv.CustomerId#(lf)        AND pi.Aprovador = CAST(dwu.WebUserSourceCode AS STRING)#(lf)        AND fms.FirstApprovalTimestamp >= pi.DataInicio#(lf)        AND (pi.DataFim IS NULL OR fms.FirstApprovalTimestamp < pi.DataFim)#(lf)    )#(lf)  )"),
				    #"Coluna Duplicada" = Table.DuplicateColumn(Fonte, "InfoPrecoParceiro", "InfoPrecoParceiro - Copiar"),
				    Personalizar1 = Table.TransformColumns(#"Coluna Duplicada", {{"InfoPrecoParceiro", each Text.BetweenDelimiters(_, """valornegociar"" : ", ","), type text}}),
				    Personalizar2 = Table.TransformColumns(#"Personalizar1", {{"InfoPrecoParceiro - Copiar", each Text.BetweenDelimiters(_, """tempovigenciameses"" : ", ","), type text}}),
				    Personalizar3 = Table.RenameColumns(#"Personalizar2",{{"InfoPrecoParceiro - Copiar", "ValidadeNegociacaoMeses"}, {"InfoPrecoParceiro", "ValorUnitarioNegociadoPrecoParceiro"}}),
				    Personalizar4 = Table.ReplaceValue(#"Personalizar3",".",",",Replacer.ReplaceText,{"ValorUnitarioNegociadoPrecoParceiro"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Personalizar4,{{"ValorUnitarioNegociadoPrecoParceiro", Currency.Type}, {"ValidadeNegociacaoMeses", Int64.Type}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado", "ValorTotalNegociadoPrecoParceiro", each [QuantidadePeca] * [ValorUnitarioNegociadoPrecoParceiro]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"DataAprovacao1OS", type date}, {"ValorTotalNegociadoPrecoParceiro", Currency.Type}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado1", each [DataAprovacao1OS] >= #date(2025, 4, 1)),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Linhas Filtradas", "DiferencaValorUnitarioReferencialXNeggociado", each [ValorUnitarioNegociadoPrecoParceiro] - [ValorUnitarioHierarquiaReferencial]),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"CodigoCliente", type text}})
				in
				    #"Tipo Alterado2"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Exception

