table RelacaoClienteAprovador
	lineageTag: 9f9556ff-b0a4-4bd9-9a26-645885f37377

	column CodigoCliente
		dataType: string
		lineageTag: 690b2511-70f5-43f1-b647-6d2b56c1a485
		summarizeBy: none
		sourceColumn: CodigoCliente

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Aprovador
		dataType: string
		lineageTag: ab8cb616-a6c2-4b59-aaa4-0d9b90d1c9c3
		summarizeBy: none
		sourceColumn: Aprovador

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column nome_aprovador
		dataType: string
		lineageTag: b04dcd09-bc95-4a58-b0e9-2f58920088fc
		summarizeBy: none
		sourceColumn: nome_aprovador

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DataInicio
		dataType: dateTime
		formatString: Short Date
		lineageTag: cd046357-7214-455d-9e2b-7ad556714935
		summarizeBy: none
		sourceColumn: DataInicio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DataFim
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5280e5ed-441a-4065-a0e7-2396a1f4a746
		summarizeBy: none
		sourceColumn: DataFim

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NomeCliente
		dataType: string
		lineageTag: 8f4b9c71-6554-4ece-926b-681ad2e60721
		summarizeBy: none
		sourceColumn: NomeCliente

		annotation SummarizationSetBy = Automatic

	partition RelacaoClienteAprovador = m
		mode: import
		source =
				let
				    Fonte = Azure(" WITH logs AS (#(lf)  SELECT#(lf)    dmplv.ClientId AS CodigoCliente,#(lf)    CAST(dmplv.ParameterLogOrgValueModificationTimestamp AS TIMESTAMP) AS ts,#(lf)    COALESCE(dmplv.OldValueDescription, '') AS old_values,#(lf)    COALESCE(dmplv.NewValueDescription, '') AS new_values#(lf)  FROM hive_metastore.gold.Dim_MaintenanceParameterLogValue AS dmplv#(lf)  WHERE dmplv.ParameterId = 586#(lf)    -- opcional: limitar a um cliente específico#(lf)    -- AND dmplv.ClientId IN (37514,150797,158555)#(lf)),#(lf)#(lf)-- Normaliza old/new em arrays (aceita ; ou , como separadores, remove espaços, vazios e duplicados)#(lf)sets AS (#(lf)  SELECT#(lf)    CodigoCliente,#(lf)    ts,#(lf)    array_distinct(#(lf)      filter(#(lf)        split(regexp_replace(old_values, '\\s+', ''), '[;,]+'),#(lf)        x -> x <> ''#(lf)      )#(lf)    ) AS old_set,#(lf)    array_distinct(#(lf)      filter(#(lf)        split(regexp_replace(new_values, '\\s+', ''), '[;,]+'),#(lf)        x -> x <> ''#(lf)      )#(lf)    ) AS new_set#(lf)  FROM logs#(lf)),#(lf)#(lf)-- Inclusões: itens presentes em new_set e ausentes em old_set (ADD)#(lf)adds AS (#(lf)  SELECT#(lf)    CodigoCliente,#(lf)    ts,#(lf)    CAST(approver AS STRING) AS approver#(lf)  FROM sets#(lf)  LATERAL VIEW explode(new_set) ns AS approver#(lf)  WHERE NOT array_contains(old_set, approver)#(lf)),#(lf)#(lf)-- Exclusões: itens presentes em old_set e ausentes em new_set (REMOVE)#(lf)removes AS (#(lf)  SELECT#(lf)    CodigoCliente,#(lf)    ts,#(lf)    CAST(approver AS STRING) AS approver#(lf)  FROM sets#(lf)  LATERAL VIEW explode(old_set) os AS approver#(lf)  WHERE NOT array_contains(new_set, approver)#(lf)),#(lf)#(lf)events AS (#(lf)  SELECT CodigoCliente, approver, ts, 'ADD'    AS event_type FROM adds#(lf)  UNION ALL#(lf)  SELECT CodigoCliente, approver, ts, 'REMOVE' AS event_type FROM removes#(lf)),#(lf)#(lf)-- Para cada cliente+aprovador, pegue o próximo evento após um ADD como DataFim#(lf)ordered AS (#(lf)  SELECT#(lf)    CodigoCliente,#(lf)    approver,#(lf)    event_type,#(lf)    ts,#(lf)    LEAD(ts) OVER (PARTITION BY CodigoCliente, approver ORDER BY ts)         AS next_ts,#(lf)    LEAD(event_type) OVER (PARTITION BY CodigoCliente, approver ORDER BY ts) AS next_event_type#(lf)  FROM events#(lf))#(lf)#(lf)SELECT#(lf)  CodigoCliente,#(lf)  dfc.CustomerShortName AS NomeCliente,#(lf)  -- Se preferir numérico:#(lf)  -- CAST(approver AS BIGINT) AS Aprovador,#(lf)  approver AS Aprovador,#(lf)  dwu.WebUserName AS nome_aprovador,#(lf)  date_format(ts, 'yyyy-MM-dd HH:mm') AS DataInicio,#(lf)  date_format(next_ts, 'yyyy-MM-dd HH:mm') AS DataFim#(lf)FROM ordered#(lf)LEFT JOIN hive_metastore.gold.dim_webusers AS dwu#(lf)  ON dwu.WebUserSourceCode = ordered.approver#(lf)LEFT JOIN hive_metastore.gold.dim_fuelcustomers AS dfc#(lf)  ON ordered.codigocliente = dfc.CustomerSourceCode#(lf)WHERE 1=1#(lf)AND event_type = 'ADD'#(lf)#(lf)ORDER BY CodigoCliente, Aprovador, DataInicio"),
				    #"Linhas Filtradas" = Table.SelectRows(Fonte, each ([CodigoCliente] <> null) and ([Aprovador] <> "0" and [Aprovador] <> "1" and [Aprovador] <> "10") and ([nome_aprovador] <> "Ebubicz")),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"CodigoCliente", type text}}),
				    #"Texto Extraído Antes do Delimitador" = Table.TransformColumns(#"Tipo Alterado", {{"DataInicio", each Text.BeforeDelimiter(_, " "), type text}}),
				    #"Texto Extraído Antes do Delimitador1" = Table.TransformColumns(#"Texto Extraído Antes do Delimitador", {{"DataFim", each Text.BeforeDelimiter(_, " "), type text}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Texto Extraído Antes do Delimitador1",{{"DataInicio", type date}, {"DataFim", type date}})
				in
				    #"Tipo Alterado1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

